config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#homepage'
  get 'about', to:'pages#about'

  resources :articles

  get 'signup', to:'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, 
            length: {minimum: 3, maximum: 59}

  validates :description, presence: true, 
            length: {minimum:10, maximum: 300}
            
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save {self.email = email.downcase }
  
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: {case_sensitice: false},
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new 
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
      flash[:notice] = 'Article was succesfully created'
      
    else
      render 'new'
    end
  end

  def update
    
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    
    @article.destroy
    flash[:notice] = "Article was succesfully deleted"
    redirect_to articles_path

  end
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article"
        redirect_to root_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have succesfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    if !logged_in?
      flash[:danger] = "Please login to perform that action"
      redirect_to root_path
    else
      @users = User.paginate(page: params[:page], per_page: 3)
    end
  end
  
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user=User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size:150})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size=options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:'img-circle')
  end

end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <%obj.each do |article|%>
    <tr>
      <td><%= article.id%></td>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if logged_in? && (current_user == article.user || current_user.admin?)%>
      <td>&nbsp;<%= link_to 'Edit', edit_article_path(article) %>&nbsp;</td>
      
      <td><%= link_to 'Delete', article_path(article), method: :delete, 
          data: {confirm: "Are you sure???"} %>&nbsp;
      </td>
      <% end %>
      <td><%= link_to 'Show', article_path(article) %>&nbsp;</td>
      
      <td>Created by: <%= article.user.username if article.user%>, 
      <%= time_ago_in_words(article.created_at) %> ago,
      Last Updated: <%= time_ago_in_words(article.updated_at)%> ago</td>
    </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<%= form_for @article do |f| %>
  <p>
    <%= f.label 'title enter kar' %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label 'Description' %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit%>
  </p>
<%end%>


[ <%= link_to "Cancel request and return to articles listing", articles_path %>]

app/views/articles/edit.html.erb
<h1>Edit selected article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<p></p>
<div align='center'>
<%= will_paginate %>
</div>
<%= render 'article', obj: @articles%>
<div align="center">
<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected Article</h1>

<p>
  Title: <%= @article.title %>
</p>
<% if @article.user%>
<ul class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <li>Created by:</li>
      <li><%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
      <li class="article-title">
        <%= link_to @article.user.username, user_path(@article.user)%>
      </li>
      <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles%>
      </small></li>
    </div>
  </div>
  </ul>
<% end %>
<p>
  Description: <%= @article.description%>
</p>
<% if logged_in? && (current_user == @article.user || current_user.admin?)%>
<%= link_to 'Edit this article', edit_article_path(@article) %> 
| <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure???"} %>
<% end %>

app/views/layouts/_login.html.erb
<% if logged_in? %>
  <%= link_to (current_user.admin? ? 'Logout (Admin)' : 'Logout'), logout_path, method: :delete %> |
  <%= link_to 'create new article', new_article_path %> |
  <%= link_to 'View your profile', user_path(current_user)%> |
  <%= link_to 'Edit your profile', edit_user_path(current_user)%>
<% else %>
  <%= link_to 'Login', login_path %> | <%= link_to 'Signup', signup_path %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path, class: "Home"%> |
    <%= link_to "All Articles", articles_path%> |
    <% if logged_in?%>
    <%= link_to "Users", users_path %> |
    <% end %>
    <%= render 'layouts/login'%>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About section of the alpha blog</h1>

app/views/pages/homepage.html.erb
<h1>This is the homepage of the alpha blog</h1>

<%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'About', about_path%>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<h2><%= pluralize(obj.errors.count, "error")%> prevented the article from getting created:</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg%></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<%= form_for @user do |f| %>
  <p>
    <%= f.label 'Username' %>
    <%= f.text_field :username, placeholder: 'Create Username' %>
  </p>
  <p>
    <%= f.label 'email' %>
    <%= f.email_field :email, placeholder: 'Enter email' %>
  </p>
  <p>
  </p>
    <%= f.label 'password'%>
    <%= f.password_field :password, placeholder: 'Create password'%>
  <p>
    <%= f.submit(@user.new_record? ? "Signup" : "Update")%>
  </p>
<%end%>


[ <%= link_to "Cancel request and return to articles listing", articles_path %>]

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<div align="center">
<%= will_paginate%>

<% @users.each do |user|%>
  <ul class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <li><%= link_to gravatar_for(user), user_path(user)%></li>
      <li class="article-title">
        <%= link_to user.username, user_path(user)%>
      </li>
      <li><small><%= pluralize(user.articles.count, "article") if user.articles%>
      </small></li>
      <% if logged_in? and current_user.admin?%>
      <li><%= link_to "Delete this user", user_path(user),
      method: :delete, data: {confirm: "Are you sure you want 
      to delete the user and all their articles" }%>
      </li>
      <li>
        <%= link_to "Edit this User", edit_user_path(user)%>
      </li>
      <% end %>
    </div>
  </div>
  </ul>

<%end%>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up form for User</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username%>'s page</h1>
<div class='row'>
  <div class='col-md-4 col-md-offset-4 center'>
    <%= gravatar_for @user%>
    <li>
    <%= "(Admin)" if current_user.admin?%>
    <small>
    <%= pluralize(@user.articles.count, "article") if @user.articles %>
      </small></li>
    <% if logged_in? and current_user.admin?%>
      <li>
        <%= link_to "Edit", edit_user_path(@user)%>
      </li>
    <% end %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>
<div align="center">
<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles%>
<div align="center">
<%= will_paginate @user_articles %>
</div>